# Site settings
title: Gaussian Process and Uncertainty Quantification Summer School, 2023
email:
description: > # this means to ignore newlines until "baseurl:"
  Gaussian Process Summer School
baseurl: "/gpss23" # the subpath of your site, e.g. /blog/
url: "https://gpss.cc" # the base hostname & protocol for your site
logo: "gpss_logo.svg"
twitter_username: sheffieldmlnet
github_username:  gpschool

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: gpschool/jekyll-theme
style: gpss

youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: gpss23

markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"
banner:

analytics:
 google:
   tracking_id: UA-62991754-1 # Google tracking ID if applicable

youtube:
  height: 315
  width: 560

conference:
  draft: false # set to True if the programme is draft only.
  hide_tentative: true
  hosts:
  short_name: GPSS
  full_name:  Gaussian Process and Uncertainty Quantification Summer School
  venue: Roscoe building
  location: Manchester, UK
  name: Gaussian Process Summer School
  year: 2023
  month: September
  dates:
  - 2023-09-11
  - 2023-09-12
  - 2023-09-13
  - 2023-09-14
  chairs:
  - type: Organizers
    people:
    - {given: Mauricio, family: Alvarez, url: "https://maalvarezl.github.io/", institute: University of Manchester}
    - {given: Carl H., family: Ek, url: "http://carlhenrik.com/", institute: University of Cambridge}
    - {given: Javier, family: Gonzalez, url: "https://javiergonzalezh.github.io/", institute: Microsoft Research Cambridge}
    - {given: Michael T., family: Smith, url: "https://www.michaeltsmith.org.uk/", institute: University of Sheffield}
    - {given: Richard, family: Wilkinson, url: "https://r-wilkinson.staff.shef.ac.uk/", institute: University of Nottingham}
    - {given: Neil D., family: Lawrence, url: "https://inverseprobability.com", institute: University of Cambridge}


previous_meeting:
  name: GPSS 2022
  url: "https://gpss.cc/gpss22"

map:
  show: false
  mapbox:
    latitude: 53.385396 # latitude of map center
    longitude: -1.472726 # longitude of map center
    map_id1: maalvarezl # mapbox id1
    map_id2: cj6hz56fb4q9l2rpajqiqw5ki # mapbox id2
    fresh: true
    title: false
    access_token: pk.eyJ1IjoibWFhbHZhcmV6bCIsImEiOiJjajY1Nmo1b3gxb2d2Mndub2dyeDNsa2IzIn0.qLCz36sKjWARW8EBSy2fAQ # mapbox access token
    zoom_level: 14.5
    width: 100%
    height: 500px
